spring:
  application:
    name: gateway-service
  profiles:
    active: dev
  main:
    web-application-type: reactive
  data:
    redis:
      host: 127.0.0.1
      port: 6379
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
server:
  port: 8000
